instrumentation:
  include-all-sources: true
  excludes: ['**/test/**']
check:
  global:
    statements: 70
    lines: 90
    branches: 60
    functions: 90
  each:
    statements: 70
    lines: 90
    branches: 60
    functions: 90
